### PR TITLE
[build] Relocate shaded jackson and other internal deps in fluss-fs-s3

### LINKED ISSUE #4072: [build] fluss-fs-s3 uber-jar bundles 1,114 unshaded jackson classes that can shadow downstream jackson
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

main (development)

### Describe the bug

The `fluss-fs-s3` uber-jar bundles `hadoop-common` and `aws-java-sdk-*`
dependencies **without any shade relocations**. As a result, 1,114 unshaded
jackson class files leak into the jar at `com/fasterxml/*` paths:

| Package | Approx. count | Source |
| --- | --- | --- |
| `com/fasterxml/jackson/databind/**` | ~800 | hadoop-common |
| `com/fasterxml/jackson/core/**` | ~200 | hadoop-common |
| `com/fasterxml/jackson/annotation/**` | ~20 | hadoop-common |
| `com/fasterxml/jackson/dataformat/cbor/**` | ~50 | aws-java-sdk-core |
| `META-INF/versions/{11,17,19}/com/fasterxml/**` (MRJ) | ~25 | jackson-core MRJ |

When a downstream application puts `fluss-fs-s3` on its classpath alongside its
own jackson-core (e.g. 2.16+), the leaked classes can shadow the application's
jackson and cause runtime failures such as `NoSuchMethodError` — the same
failure mode reported in #3553 for the MRJ entries, but here affecting the full
jackson-databind/core/annotations/cbor surface, not just MRJ entries.

In contrast, `fluss-fs-hadoop-shaded` already relocates these same packages
(`com.fasterxml`, `org.codehaus`, `com.ctc`, `com.google.re2j`,
`org.apache.htrace`) into `org.apache.fluss.fs.shaded.hadoop3.*`.

### To Reproduce

```bash
./mvnw -pl fluss-filesystems/fluss-fs-s3 -am -DskipTests package
unzip -l fluss-filesystems/fluss-fs-s3/target/fluss-fs-s3-*.jar | grep -c " com/fasterxml"
# -> 1114
```

### Expected behavior

All bundled third-party dependencies should be relocated under Fluss's shaded
namespace (mirroring the `fluss-fs-hadoop-shaded` pattern), so the uber-jar
never exposes `com/fasterxml/*` classes on the classpath.

### Additional context

- Same issue class as #3553 (MRJ entries escaping shade relocation), but a
  larger surface: the entire jackson family is unshaded, not just MRJ entries.
- Other filesystem plugins (`fluss-fs-oss`, `fluss-fs-gs`, `fluss-fs-azure`,
  `fluss-fs-obs`, `fluss-fs-cos`, `fluss-fs-hdfs`) may have the same gap; can
  be checked in follow-ups.

### Solution

Mirror the `fluss-fs-hadoop-shaded` approach: add `maven-shade-plugin`
relocations for `com.fasterxml.jackson.*`, `com.fasterxml.jackson.databind.*`,
`com.fasterxml.jackson.dataformat.cbor.*` to `org.apache.fluss.fs.shaded.s3.*`,
and add a `<filter>` to exclude `META-INF/versions/*/com/fasterxml/**` (MRJ
entries are not relocated by the shade plugin). A draft PR is in progress.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Jackeyzhe**
### Purpose

Linked issue: close #4072

The `fluss-fs-s3` uber-jar bundles `hadoop-common` and `aws-java-sdk-*`
dependencies without relocations for jackson and several other bundled
third-party packages, leaking 1,050 unshaded jackson class files
(`jackson-databind`, `jackson-core`,
`jackson-annotations`, `jackson-dataformat-cbor`) at `com/fasterxml/*`
paths. These can shadow a downstream application's own jackson-core
(e.g. 2.16+) and cause runtime failures such as `NoSuchMethodError`.

### Brief change log

`fluss-filesystems/fluss-fs-s3/pom.xml`:

- Added shade relocations for the transitively-bundled third-party
  packages, consolidated into the **single `<relocations>` block** and
  namespaced under `org.apache.fluss.shaded.*` (aligned with the
  pre-existing `org.apache.commons` relocation on `main`):
  - `com.fasterxml` → `org.apache.fluss.shaded.com.fasterxml`
  - `org.apache.htrace` → `org.apache.fluss.shaded.org.apache.htrace`
  - `com.ctc` → `org.apache.fluss.shaded.com.ctc`
  - `com.google.common` / `com.google.re2j` / `com.google.j2objc` /
    `com.google.thirdparty` → `org.apache.fluss.shaded.com.google.*`
    (narrowed from the broad `com.google` namespace so references to
    un-bundled `protobuf`/`gson` are **not** rewritten to a dangling path)
  - `org.apache.commons` → only the **8** commons packages actually bundled
    in this jar: `codec`, `collections4`, `compress`, `configuration2`,
    `io`, `lang3`, `logging`, `text` (narrowed from the broad
    `org.apache.commons` namespace so references to un-bundled
    `commons-cli` / `commons-jxpath` / `commons-math3` etc. are **not**
    rewritten to a dangling path)
  - `org.codehaus` → only `stax2` and `mojo`, the two `org.codehaus`
    packages actually bundled in this jar (124 + 1 classes).
    `org.codehaus.jackson` is referenced by Hadoop (e.g.
    `MetricsJsonBuilder`) but is **not** packaged here, so it is left
    un-relocated, preserving the pre-change external classpath resolution
- Added a `<filter>` excluding `META-INF/versions/**/com/fasterxml/**`:
  the Maven Shade Plugin relocates base-path classes but not
  Multi-Release JAR entries (same issue class as #3553, which affected
  `fluss-shaded-jackson`). The relocated base-path implementation is
  sufficient for all Java versions.

### Tests

Build-only change (pom.xml), verified by inspecting the produced jar:

- Before fix: 1,050 unshaded `com/fasterxml` class entries
- After fix: 0 unshaded `com/fasterxml` entries (base path and MRJ);
  1,050 jackson classes correctly relocated to
  `org/apache/fluss/shaded/com/fasterxml/*`
- No dangling class references remain: `protobuf`/`gson`,
  `commons-cli`/`jxpath`/`math3`, and `org.codehaus.jackson` are not
  rewritten. The checker reports two non-class commons-codec resource
  strings (`language/bm/` and `language/dmrules`); both resources are present
  at their relocated paths in the produced jar
- Bytecode references inside the bundled AWS SDK / Hadoop classes are
  rewritten to the shaded path (verified via `javap` on sampled classes)
- Intentional `jaxb-api` MRJ entries under `META-INF/versions/**` are
  preserved untouched
- `./mvnw spotless:check` passes

### API and Format

No API or storage format changes. This only affects the internal shading
layout of the `fluss-fs-s3` uber-jar; all relocated classes move under
the `org.apache.fluss.shaded` namespace.

### Documentation

No new feature introduced; no documentation changes required.

### CODE REVIEW

File: fluss-filesystems/fluss-fs-s3/pom.xml [hunk 1]
```diff
@@ -344,6 +344,41 @@
                                     <include>*:*</include>
                                 </includes>
                             </artifactSet>
+                            <relocations>
+                                <!-- relocate the packages that are internal to Hadoop/AWS SDK
+                                     and not used / exposed downstream, mirroring the pattern
+                                     of fluss-fs-hadoop-shaded -->
+                                <relocation>
+                                    <pattern>com.google.re2j</pattern>
```
Comment (litiliu) [inline fluss-filesystems/fluss-fs-s3/pom.xml:358]: would it be better to shaded the whole com.google(including re2j and common)?

Comment (Jackeyzhe) [reply fluss-filesystems/fluss-fs-s3/pom.xml:358]: Good catch — agreed, widened to the whole com.google namespace
(a6215ed2a). It turns out the jar was still leaking 1,974 unshaded
com.google.common (Guava) entries plus j2objc / thirdparty, which
is the same shadowing bug class as the jackson leak in #4072.

Verified: 0 unshaded com/google entries (base path and MRJ), all
constant-pool references rewritten to the shaded path, and hadoop's
own org.apache.hadoop.thirdparty.com.google namespace left untouched.

While verifying I also noticed fluss-fs-hdfs has the same problem
at a larger scale (1,073 unshaded com/fasterxml + 2,731 com/google
in its uber-jar) — I'll file a separate issue for that so this PR
stays scoped to fluss-fs-s3.

Comment (Jackeyzhe) [reply fluss-filesystems/fluss-fs-s3/pom.xml:358]: Filed #4116 for the fluss-filesystems shading leak (all 7 plugins verified leaked, gs worst)
so #4073 stays scoped to s3 — thanks again for the catch, @litiliu.

**Review by binary-signal — APPROVED** [review]
@Jackeyzhe thank you for addressing this issue, I've left some comments

File: fluss-filesystems/fluss-fs-s3/pom.xml [hunk 2]
```diff
@@ -344,6 +344,41 @@
...
+                                        org.apache.fluss.fs.shaded.s3.org.codehaus
+                                    </shadedPattern>
+                                </relocation>
+                                <relocation>
+                                    <pattern>com.ctc</pattern>
+                                    <shadedPattern>
+                                        org.apache.fluss.fs.shaded.s3.com.ctc
+                                    </shadedPattern>
+                                </relocation>
+                            </relocations>
```
Comment (binary-signal) [inline fluss-filesystems/fluss-fs-s3/pom.xml]: The shade plugin rewrites **every reference** matching a `<relocation>` pattern, including references to classes the jar does not contain. `fluss-fs-s3` bundles only
  four `com.google.*` packages:

  | package | classes bundled |
  |---|---|
  | `com.google.common` | 1974 |
  | `com.google.re2j` | 48 |
  | `com.google.j2objc` | 14 |
  | `com.google.thirdparty` | 5 |

  But the bundled Hadoop and AWS SDK code *references* `com.google.protobuf` and `com.google.gson`, neither of which is packaged (both are `<exclusion>`s in this pom).
  After this PR, those references are rewritten to `org.apache.fluss.fs.shaded.s3.com.google.protobuf.*` — about ~40ish distinct classes, e.g.:

  ```
  org/apache/fluss/fs/shaded/s3/com/google/protobuf/Message                (11 refs)
  org/apache/fluss/fs/shaded/s3/com/google/protobuf/Descriptors            (5 refs)
  org/apache/fluss/fs/shaded/s3/com/google/protobuf/GeneratedMessage       (5 refs)
  org/apache/fluss/fs/shaded/s3/com/google/gson/stream/JsonReader          (1 ref)
  ```


For example before relocation, `com.google.protobuf.Message` is a soft dependency: absent from the uber-jar, but resolvable if the surrounding classpath or plugin parent
  classloader provides it. After relocation the reference points at a coordinate **nothing will ever provide**, because no artifact anywhere publishes
  `org.apache.fluss.fs.shaded.s3.com.google.protobuf`. A previously satisfiable link becomes a `NoClassDefFoundError` on any code path that touches it.

 I hit this problem with the sibling `org.apache.commons` relocation (added in #3960, already on `main`) while try to extend this PR's approach to the other filesystem plugins:

  ```
  java.lang.NoClassDefFoundError: org/apache/fluss/shaded/org/apache/commons/cli/ParseException
      at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1713)
      at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNode(MiniDFSCluster.java:1374)
      ...
      at org.apache.fluss.fs.hdfs.HdfsBehaviorTest.createHDFS(HdfsBehaviorTest.java:62)
  ```

  `commons-cli` *was* on the classpath. The reference had simply been rewritten to a name that does not exist.


 I was able to ~ fix ~ by relocating the packages that are actually bundled rather than the `com.google` prefix:

  ```xml
  <relocation>
      <pattern>com.google.common</pattern>
      <shadedPattern>org.apache.fluss.fs.shaded.s3.com.google.common</shadedPattern>
  </relocation>
  <relocation>
      <pattern>com.google.j2objc</pattern>
      <shadedPattern>org.apache.fluss.fs.shaded.s3.com.google.j2objc</shadedPattern>
  </relocation>
  <relocation>
      <pattern>com.google.thirdparty</pattern>
      <shadedPattern>org.apache.fluss.fs.shaded.s3.com.google.thirdparty</shadedPattern>
  </relocation>
  <relocation>
      <pattern>com.google.re2j</pattern>
      <shadedPattern>org.apache.fluss.fs.shaded.s3.com.google.re2j</shadedPattern>
  </relocation>
  ```

  This keeps the guava fix   and drops the dangling protobuf/gson links. It also matches what `fluss-fs-hadoop-shaded` already
  does, which the PR description cites as the pattern being mirrored: that module relocates `com.google.re2j` specifically, not `com.google`.

**Comment by binary-signal** [comment]
I applied this PR locally on top of `main` (`4e372d5c7`) and can confirm it does what it says: `fluss-fs-s3` goes from 1050 unshaded `com/fasterxml` classes to 0, with 1974 guava, 48 re2j, 205 ctc and 125 codehaus classes correctly relocated under `org.apache.fluss.fs.shaded.s3`. 

One thing worth addressing before merge, though.

### `com.google` is broader than what the jar actually bundles

The shade plugin rewrites **every reference** matching a `<relocation>` pattern, including references to classes the jar does not contain. `fluss-fs-s3` bundles only four `com.google.*` packages:

| package | classes bundled |
|---|---|
| `com.google.common` | 1974 |
| `com.google.re2j` | 48 |
| `com.google.j2objc` | 14 |
| `com.google.thirdparty` | 5 |

But the bundled Hadoop and AWS SDK code *references* `com.google.protobuf` and `com.google.gson`, neither of which is packaged (both are `<exclusion>`s in this pom). After this PR, those references are rewritten to `org.apache.fluss.fs.shaded.s3.com.google.protobuf.*` — about 40 distinct classes, e.g.:

```
org/apache/fluss/fs/shaded/s3/com/google/protobuf/Message                (11 refs)
org/apache/fluss/fs/shaded/s3/com/google/protobuf/Descriptors            (5 refs)
org/apache/fluss/fs/shaded/s3/com/google/protobuf/GeneratedMessage       (5 refs)
org/apache/fluss/fs/shaded/s3/com/google/gson/stream/JsonReader          (1 ref)
```


Before relocation, `com.google.protobuf.Message` is a soft dependency: absent from the uber-jar, but resolvable if the surrounding classpath or plugin parent classloader provides it. After relocation the reference points at a coordinate **nothing will ever provide**, because no artifact anywhere publishes `org.apache.fluss.fs.shaded.s3.com.google.protobuf`. A previously-satisfiable link becomes a guaranteed `NoClassDefFoundError` on any code path that touches it.

This is not hypothetical. I hit exactly this mechanism via the sibling `org.apache.commons` relocation (added in #3960, already on `main`) while extending this PR's approach to the other filesystem plugins:

```
java.lang.NoClassDefFoundError: org/apache/fluss/shaded/org/apache/commons/cli/ParseException
    at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1713)
    at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNode(MiniDFSCluster.java:1374)
    ...
    at org.apache.fluss.fs.hdfs.HdfsBehaviorTest.createHDFS(HdfsBehaviorTest.java:62)
```

`commons-cli` *was* on the classpath. The reference had simply been rewritten to a name that does not exist.

To make this checkable , #4144 adds `tools/ci/check_shaded_jars.py`, whose `--dangling` mode reports exactly this: relocated class references a jar does not contain. Running it on `fluss-fs-s3` built from this PR lists 92 such classes, 83 of them real classes rather than annotations.

### Suggested change

Name the packages that are actually bundled rather than the `com.google` prefix:

```xml
<relocation>
    <pattern>com.google.common</pattern>
    <shadedPattern>org.apache.fluss.fs.shaded.s3.com.google.common</shadedPattern>
</relocation>
<relocation>
    <pattern>com.google.j2objc</pattern>
    <shadedPattern>org.apache.fluss.fs.shaded.s3.com.google.j2objc</shadedPattern>
</relocation>
<relocation>
    <pattern>com.google.thirdparty</pattern>
    <shadedPattern>org.apache.fluss.fs.shaded.s3.com.google.thirdparty</shadedPattern>
</relocation>
<relocation>
    <pattern>com.google.re2j</pattern>
    <shadedPattern>org.apache.fluss.fs.shaded.s3.com.google.re2j</shadedPattern>
</relocation>
```

This keeps the full guava fix (the actual win here — 1974 classes) and drops the dangling protobuf/gson links. It also matches what `fluss-fs-hadoop-shaded` already does, which the PR description cites as the pattern being mirrored: that module relocates `com.google.re2j` specifically, not `com.google`.

The same applies to the existing `org.apache.commons` relocation from #3960, which leaves dangling references to `commons-cli`, `commons-codec`, `commons-math3`, `commons-net`, `commons-jxpath`, `commons-jexl2` and `commons-vfs2` in every filesystem plugin. That is pre-existing rather than something this PR introduces; it is written up in #4143 along with the rest of the shading leaks.

#4144 applies the narrow-pattern approach across the modules #4143 covers, if a worked example is useful — every relocation there names the packages actually bundled, and `io.netty.internal.tcnative` and `org.apache.arrow` are excluded for the JNI reason above. It deliberately leaves `fluss-fs-s3` to this PR.

### Two notes for anyone verifying locally

- **`clean` is required.** An incremental build reuses already-relocated classes in `target/classes`, so a narrowed pattern appears to have no effect until you run `mvn clean`. This cost me a couple of confusing debug cycles.
- `mvn test -pl fluss-filesystems -amd` fails on `HadoopUtilsTest` independently of any of this: in a reactor containing `fluss-fs-hadoop-shaded`, dependent modules get its unshaded `target/classes` because `shade` runs at `package`. Use `verify` or `install` instead. Reproduces on unmodified `main`.

The MRJ exclusion in this PR is also worth keeping even alongside #3884's global one — #3884 puts it in the root pom under `<filters combine.children="append">`, so it already cascades here, but the local copy keeps this PR correct on its own.

**Comment by Jackeyzhe** [comment]
> I applied this PR locally on top of `main` (`4e372d5c7`) and can confirm it does what it says: `fluss-fs-s3` goes from 1050 unshaded `com/fasterxml` classes to 0, with 1974 guava, 48 re2j, 205 ctc and 125 codehaus classes correctly relocated under `org.apache.fluss.fs.shaded.s3`.
> 
> One thing worth addressing before merge, though.
> 
> ### `com.google` is broader than what the jar actually bundles
> The shade plugin rewrites **every reference** matching a `<relocation>` pattern, including references to classes the jar does not contain. `fluss-fs-s3` bundles only four `com.google.*` packages:
> 
> package	classes bundled
> `com.google.common`	1974
> `com.google.re2j`	48
> `com.google.j2objc`	14
> `com.google.thirdparty`	5
> But the bundled Hadoop and AWS SDK code _references_ `com.google.protobuf` and `com.google.gson`, neither of which is packaged (both are `<exclusion>`s in this pom). After this PR, those references are rewritten to `org.apache.fluss.fs.shaded.s3.com.google.protobuf.*` — about 40 distinct classes, e.g.:
> 
> ```
> org/apache/fluss/fs/shaded/s3/com/google/protobuf/Message                (11 refs)
> org/apache/fluss/fs/shaded/s3/com/google/protobuf/Descriptors            (5 refs)
> org/apache/fluss/fs/shaded/s3/com/google/protobuf/GeneratedMessage       (5 refs)
> org/apache/fluss/fs/shaded/s3/com/google/gson/stream/JsonReader          (1 ref)
> ```
> 
> Before relocation, `com.google.protobuf.Message` is a soft dependency: absent from the uber-jar, but resolvable if the surrounding classpath or plugin parent classloader provides it. After relocation the reference points at a coordinate **nothing will ever provide**, because no artifact anywhere publishes `org.apache.fluss.fs.shaded.s3.com.google.protobuf`. A previously-satisfiable link becomes a guaranteed `NoClassDefFoundError` on any code path that touches it.
> 
> This is not hypothetical. I hit exactly this mechanism via the sibling `org.apache.commons` relocation (added in #3960, already on `main`) while extending this PR's approach to the other filesystem plugins:
> 
> ```
> java.lang.NoClassDefFoundError: org/apache/fluss/shaded/org/apache/commons/cli/ParseException
>     at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1713)
>     at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNode(MiniDFSCluster.java:1374)
>     ...
>     at org.apache.fluss.fs.hdfs.HdfsBehaviorTest.createHDFS(HdfsBehaviorTest.java:62)
> ```
> 
> `commons-cli` _was_ on the classpath. The reference had simply been rewritten to a name that does not exist.
> 
> To make this checkable , #4144 adds `tools/ci/check_shaded_jars.py`, whose `--dangling` mode reports exactly this: relocated class references a jar does not contain. Running it on `fluss-fs-s3` built from this PR lists 92 such classes, 83 of them real classes rather than annotations.
> 
> ### Suggested change
> Name the packages that are actually bundled rather than the `com.google` prefix:
> 
> ```
> <relocation>
>     <pattern>com.google.common</pattern>
>     <shadedPattern>org.apache.fluss.fs.shaded.s3.com.google.common</shadedPattern>
> </relocation>
> <relocation>
>     <pattern>com.google.j2objc</pattern>
>     <shadedPattern>org.apache.fluss.fs.shaded.s3.com.google.j2objc</shadedPattern>
> </relocation>
> <relocation>
>     <pattern>com.google.thirdparty</pattern>
>     <shadedPattern>org.apache.fluss.fs.shaded.s3.com.google.thirdparty</shadedPattern>
> </relocation>
> <relocation>
>     <pattern>com.google.re2j</pattern>
>     <shadedPattern>org.apache.fluss.fs.shaded.s3.com.google.re2j</shadedPattern>
> </relocation>
> ```
> 
> This keeps the full guava fix (the actual win here — 1974 classes) and drops the dangling protobuf/gson links. It also matches what `fluss-fs-hadoop-shaded` already does, which the PR description cites as the pattern being mirrored: that module relocates `com.google.re2j` specifically, not `com.google`.
> 
> The same applies to the existing `org.apache.commons` relocation from #3960, which leaves dangling references to `commons-cli`, `commons-codec`, `commons-math3`, `commons-net`, `commons-jxpath`, `commons-jexl2` and `commons-vfs2` in every filesystem plugin. That is pre-existing rather than something this PR introduces; it is written up in #4143 along with the rest of the shading leaks.
> 
> #4144 applies the narrow-pattern approach across the modules #4143 covers, if a worked example is useful — every relocation there names the packages actually bundled, and `io.netty.internal.tcnative` and `org.apache.arrow` are excluded for the JNI reason above. It deliberately leaves `fluss-fs-s3` to this PR.
> 
> ### Two notes for anyone verifying locally
> * **`clean` is required.** An incremental build reuses already-relocated classes in `target/classes`, so a narrowed pattern appears to have no effect until you run `mvn clean`. This cost me a couple of confusing debug cycles.
> * `mvn test -pl fluss-filesystems -amd` fails on `HadoopUtilsTest` independently of any of this: in a reactor containing `fluss-fs-hadoop-shaded`, dependent modules get its unshaded `target/classes` because `shade` runs at `package`. Use `verify` or `install` instead. Reproduces on unmodified `main`.
> 
> The MRJ exclusion in this PR is also worth keeping even alongside #3884's global one — #3884 puts it in the root pom under `<filters combine.children="append">`, so it already cascades here, but the local copy keeps this PR correct on its own.

Thanks @binary-signal for the detailed analysis and for adding the checker in
#4144. I've addressed the broad-relocation issue in `46fd4970e`.

The broad `com.google` relocation is now limited to the four packages that
fs-s3 actually bundles: `com.google.common`, `com.google.re2j`,
`com.google.j2objc`, and `com.google.thirdparty`. I also narrowed
`org.codehaus` to `stax2` and `mojo`, and the pre-existing
`org.apache.commons` relocation to the nine commons packages present in the
jar. All relocated packages now use the shared `org.apache.fluss.shaded.*`
namespace.

After a clean rebuild, the jar contains 0 unshaded jackson entries and all
1,954 bundled guava classes remain relocated. References to non-bundled
protobuf/gson, commons-cli/jxpath/math3, and `org.codehaus.jackson` are no
longer rewritten to shaded paths. The checker's only two remaining reports
are commons-codec resource strings, and both resources are present at their
relocated paths in the jar.

I'll keep #4073 scoped to fs-s3 and leave the broader filesystem-family work
to #4143/#4144.
